name: nexarrive
description: A modern bus tracking application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  google_fonts: ^6.1.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  go_router: ^14.8.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0
  icons_launcher: ^3.0.1
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon.png
    - assets/splash.json
    - .env

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icon.png"
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/icon.png"
    ios:
      enable: true
      image_path: "assets/icon.png"
    web:
      enable: true
      image_path: "assets/icon.png"
      favicon: true 